#!/bin/sh
# PROVIDE: wgwd
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr
name=wgwd
rcvar=${name}_enable
command="/usr/local/bin/wgwd"
pidfile="/var/run/${name}.pid"
start_cmd="${name}_start"

# env
W_REMOTE_INTERFACE="xxx"
W_WG_INTERFACE="xxx"
W_ID="xxx"
W_ENDPOINT="xxx"
N_INTERVAL="5m"

wgwd_start() {
  echo "Starting ${name}."
  /usr/sbin/daemon -cf -p ${pidfile} ${command} get -remote_interface=${W_REMOTE_INTERFACE} -wg_interface=${W_WG_INTERFACE} -interval=${N_INTERVAL} nconnect -id=${W_ID} -endpoint=${W_ENDPOINT} -allow_insecure
}

load_rc_config $name
run_rc_command "$1"
