#!/bin/sh
# PROVIDE: wgwd_s3
# REQUIRE: DAEMON NETWORKING

. /etc/rc.subr
name=wgwd_s3
rcvar=${name}_enable
command="/usr/local/bin/wgwd"
pidfile="/var/run/${name}.pid"
start_cmd="${name}_start"

# env
W_REMOTE_INTERFACE="xxx"
W_WG_INTERFACE="xxx"
W_ENDPOINT="xxx"
W_ACCESS_KEY_ID="xxx"
W_SECRET_ACCESS_KEY="xxx"
W_BUCKET="xxx"
W_OBJECT_PATH="xxx"
W_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

wgwd_s3_start() {
  echo "Starting ${name}."
  /usr/sbin/daemon -cf -p ${pidfile} ${command} get -remote_interface=${W_REMOTE_INTERFACE} -wg_interface=${W_WG_INTERFACE} -interval=${N_INTERVAL} s3 -endpoint=${W_ENDPOINT} -path_style -access_key_id=${W_ACCESS_KEY_ID} -secret_access_key=${W_SECRET_ACCESS_KEY} -bucket=${W_BUCKET} -object_path=${W_OBJECT_PATH} -encryption_key=${W_ENCRYPTION_KEY}
}

load_rc_config $name
run_rc_command "$1"
