#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

W_REMOTE_INTERFACE="xxx"
W_WG_INTERFACE="xxx"
W_ENDPOINT="xxx"
W_USERNAME="xxx"
W_PASSWORD="xxx"
W_FILEPATH="xxx"
W_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

service_data() {
    echo "wgwd is starting up..."
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/local/bin/wgwd
    procd_append_param command get -remote_interface=${W_REMOTE_INTERFACE} -wg_interface=${W_WG_INTERFACE} -interval=${N_INTERVAL} webdav -endpoint=${W_ENDPOINT} -username=${W_USERNAME} -password=${W_PASSWORD} -filepath=${W_FILEPATH} -encryption_key=${W_ENCRYPTION_KEY}
    procd_set_param pidfile /var/run/wgwd.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
