#!/bin/sh /etc/rc.common

START=90
STOP=01
USE_PROCD=1

W_REMOTE_INTERFACE="xxx"
W_WG_INTERFACE="xxx"
W_ENDPOINT="xxx"
W_ACCESS_KEY_ID="xxx"
W_SECRET_ACCESS_KEY="xxx"
W_BUCKET="xxx"
W_OBJECT_PATH="xxx"
W_ENCRYPTION_KEY="xxx"
N_INTERVAL="5m"

service_data() {
    echo "wgwd is starting up..."
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/local/bin/wgwd
    procd_append_param command get -remote_interface=${W_REMOTE_INTERFACE} -wg_interface=${W_WG_INTERFACE} -interval=${N_INTERVAL} s3 -endpoint=${W_ENDPOINT} -path_style -access_key_id=${W_ACCESS_KEY_ID} -secret_access_key=${W_SECRET_ACCESS_KEY} -bucket=${W_BUCKET} -object_path=${W_OBJECT_PATH} -encryption_key=${W_ENCRYPTION_KEY}
    procd_set_param pidfile /var/run/wgwd.pid
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
