#!/bin/sh /etc/rc.common
START=90
USE_PROCD=1
COMMAND="/usr/bin/wgwd"
Command_Args="get -remote_interface=pppoe0 -wg_interface=wg0 -interval=5m webdav -endpoint=https://192.168.1.2/ -username=admin -password=adminadmin -filepath=/dav/center.json -encryption_key=adminadmin"

start_service() {
  procd_open_instance
  procd_set_param respawn
  procd_set_param command "$COMMAND" $Command_Args
  procd_close_instance
}